### ISSUE TITLE
[Feature Request] AUR Release

### ISSUE THREAD

**Issue by 0x0D15** [jonaburg/picom#2]
Would you consider adding this picom fork to the AUR?

**Comment by ceuk** [comment]
Here you go in the meantime, quick and dirty :)

#### install-picom.sh
```bash
#!/bin/bash
echo "Cloning repository from Github"
git clone https://github.com/jonaburg/picom.git $HOME/.local/share/picom
echo "Installing dependencies"
sudo pacman -S meson gcc ninja libconfig dbus libev libglvnd libx11 libxcb libxdg-basedir libxext pcre pixman xcb-util-image xcb-util-renderutil asciidoc mesa uthash xorgproto xorg-xprop xorg-xwininfo
cd ~/.local/share/picom
git submodule update --init --recursive
echo "Building"
meson --buildtype=release . build
sudo ninja -C build
echo "Installing"
sudo ninja -C build install
echo "Done"
```

#### update-picom.sh
```bash
#!/bin/bash
echo "Updating from Github"
cd $HOME/.local/share/picom
git pull origin next
git submodule update --init --recursive
sudo ninja -C build
sudo ninja -C build install
```

**Comment by jonaburg** [comment]
I don't mind making an AUR package as soon as most of the larger bugs are ironed out. At the moment it's very experimental, and the code itself, albeit working, is messy. After that's more or less resolved, and the animation code is tied up in a bool, I'll be happy to either make it as a package, or see if anyone upstream is happy in having this feature added :)

**Comment by Bug-Reaper** [comment]
Thank you!  @ceuk & @jonaburg
