### ISSUE TITLE
Entire screen blurs when selecting screen region for screenshot with xfce4-screenshooter

### ISSUE THREAD

**Issue by vhsdream** [jonaburg/picom#23]
### Platform
ArcoLinux (Arch) 64-bit, 5.9.13 kernel, Intel 4702MQ (haswell)
Lenovo Thinkpad T440p

### GPU, drivers, and screen setup

Intel Integrated Graphics
**Video drivers:**
xf86-video-amdgpu 19.1.0-2
xf86-video-ati 1:19.1.0-2
xf86-video-fbdev 0.5.0-2
xf86-video-intel 1:2.99.917+913+g9236c582-1
xf86-video-nouveau 1.0.16-2
xf86-video-openchrome 0.6.0-4
xf86-video-vesa 2.5.0-1
xf86-video-vmware 13.3.0-2

**glxinfo:**
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2) (0x416)
    Version: 20.3.0
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 20.3.0
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 20.3.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 20.3.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
### Environment

**Desktop Environment**
Qtile version 0.16.1-2 with some xfce4 apps

### picom version

vgit-a8445

### Configuration:
```
Literally the example config that is provided
```

### Steps of reproduction

1. Open xfce4-screenshooter
2. Select the 'select a region' option
3. See the entire screen blur

### Expected behavior
Screen does not blur when taking a screenshot

### Current Behavior
Entire screen blurs, preventing a clear screenshot

### Other details

Screenshot of entire screen (working):
![screen](https://user-images.githubusercontent.com/67816022/101686984-0cee2000-3a27-11eb-8935-854654a6fa51.png)

Screenshot of region:
![blurred](https://user-images.githubusercontent.com/67816022/101687001-14adc480-3a27-11eb-93ce-60ce4f107330.png)

**Comment by codiac-killer** [comment]
That happens because screeshooter overlays a "window" on top of the screen for you to select the area, this window is transparent so picom blurs it.

In oreder to fix it just add the following rule to your picom config, under **blur-background-exclude** :
`  "class_g = 'Xfce4-screenshooter'",`

**Comment by vhsdream** [comment]
> That happens because screeshooter overlays a "window" on top of the screen for you to select the area, this window is transparent so picom blurs it.
> 
> In oreder to fix it just add the following rule to your picom config, under **blur-background-exclude** :
> ` "class_g = 'Xfce4-screenshooter'",`

You've fixed this for me. Thank you kindly! Closing this non-issue now.
