### ISSUE TITLE
Usind awesome WM and the wibar is still visible while playing video in vlc and youtube ??

### ISSUE THREAD

**Issue by z3n-k3rn3l** [jonaburg/picom#33]
Installed latest version of this picom everything works fine but while playing video I can see the WIBAR/status bar at the top. For youtube as well as vlc, see image below. Also where I can tweak this setting, is the config file still in ~/.config/picom/picom.conf.
![problem](https://user-images.githubusercontent.com/75212700/104867268-82260c80-5966-11eb-9b40-3ef5ea3671e6.png)

**Comment by jonaburg** [comment]
You can find a sample of the picom.conf called 'picom.sample.conf' that comes with this fork. This does not seem to be an issue of this fork of picom in particular, but I can suggest a few things. 

Try checking the unredirect settings in the picom conf and playing around with those to see differences. If that's fine, it might be related to your awesome config. Check in rc.lua for your wibar's declarative properties for ontop = true set. Make sure you don't have something similar:

client.connect_signal("property::fullscreen", function(c)
   if c.class == "VLC" then
      c.ontop = true
   end
end)

**Comment by z3n-k3rn3l** [comment]
Thanks for your reply. I will try these and come back with the result.
